"""Supported cross-module durable execution contracts."""

from engrammesh.modules.runtime.domain.model import (
    AgentDefinition,
    AgentInvocation,
    AgentOutcome,
    Budget,
    Decision,
    ExecutionSnapshot,
    ExecutionSpec,
    ExecutionStatus,
    Failure,
    FailureCategory,
    JoinKind,
    NodeKind,
    NodeStatus,
    Plan,
    PlanDelta,
    PlanEdge,
    PlanNode,
    PlanOperation,
    SideEffectClass,
    Suspension,
    SuspensionKind,
    ToolCall,
    ToolDescriptor,
    ToolResult,
    derive_effect_id,
)
from engrammesh.modules.runtime.domain.state import (
    can_transition_execution,
    can_transition_node,
)

__all__ = (
    "AgentDefinition",
    "AgentInvocation",
    "AgentOutcome",
    "Budget",
    "Decision",
    "ExecutionSnapshot",
    "ExecutionSpec",
    "ExecutionStatus",
    "Failure",
    "FailureCategory",
    "JoinKind",
    "NodeKind",
    "NodeStatus",
    "Plan",
    "PlanDelta",
    "PlanEdge",
    "PlanNode",
    "PlanOperation",
    "SideEffectClass",
    "Suspension",
    "SuspensionKind",
    "ToolCall",
    "ToolDescriptor",
    "ToolResult",
    "can_transition_execution",
    "can_transition_node",
    "derive_effect_id",
)
